### ISSUE TITLE
Creating realm via ssoadm ends with ConfigurationException

### ISSUE THREAD

**Issue by fyrbach** [WrenSecurity/wrenam#77]
Creating realm via ssoadm ends with error. The realm itself is created but its not fully configured – there are missing Data Store, authentication modules…

```console
$ ./ssoadm create-realm -u amAdmin -f /path/to/pwd.txt -e /foobar

Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.forgerock.openam.notifications.NotificationBroker annotated with interface org.forgerock.openam.notifications.LocalOnly was bound.
  while locating org.forgerock.openam.notifications.NotificationBroker annotated with interface org.forgerock.openam.notifications.LocalOnly

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1009)
        at org.forgerock.guice.core.InjectorHolder.getInstance(InjectorHolder.java:97)
        at com.sun.identity.idm.plugins.internal.AgentsRepo.<init>(AgentsRepo.java:184)
        at com.sun.identity.sm.OrganizationConfigManager.createSubOrganization(OrganizationConfigManager.java:341)
        at com.sun.identity.cli.realm.CreateRealm.handleRequest(CreateRealm.java:86)
        at com.sun.identity.cli.SubCommand.execute(SubCommand.java:296)
        at com.sun.identity.cli.CLIRequest.process(CLIRequest.java:217)
        at com.sun.identity.cli.CLIRequest.process(CLIRequest.java:139)
        at com.sun.identity.cli.CommandManager.serviceRequestQueue(CommandManager.java:581)
        at com.sun.identity.cli.CommandManager.<init>(CommandManager.java:178)
        at com.sun.identity.cli.CommandManager.main(CommandManager.java:155)
```

**Comment by pavelhoral** [comment]
There is something fishy going on with the overall RPC services... basic `list-servers` command takes up to 30 seconds. I will probably try to this call first and then check what is going on with `create-realm`.

<details>
<summary>Access log when calling list-servers (2nd number is response duration)</summary>

```
127.0.0.1 - - [15/Feb/2023:19:04:22 +0100] "POST /openam/namingservice HTTP/1.1" 200 28 3258
127.0.0.1 - - [15/Feb/2023:19:04:22 +0100] "POST /openam/namingservice HTTP/1.1" 200 3 3258
127.0.0.1 - - [15/Feb/2023:19:04:22 +0100] "POST /openam/authservice HTTP/1.1" 200 27 605
127.0.0.1 - - [15/Feb/2023:19:04:22 +0100] "POST /openam/authservice HTTP/1.1" 200 68 2079
127.0.0.1 - - [15/Feb/2023:19:04:22 +0100] "POST /openam/sessionservice HTTP/1.1" 200 10 2047
127.0.0.1 - - [15/Feb/2023:19:04:22 +0100] "POST /openam/sessionservice HTTP/1.1" 200 2 265
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/authservice HTTP/1.1" 200 20 939
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/authservice HTTP/1.1" 200 60 1999
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/sessionservice HTTP/1.1" 200 4 1983
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/sessionservice HTTP/1.1" 200 4 265
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/sessionservice HTTP/1.1" 200 5 1984
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/json/global-audit/authentication?_action=create HTTP/1.1" 201 20 12
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/json/global-audit/access?_action=create HTTP/1.1" 201 21 12
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 187 -
127.0.0.1 - - [15/Feb/2023:19:04:23 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 182 -
127.0.0.1 - - [15/Feb/2023:19:04:24 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:24 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:25 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:25 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:26 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:26 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:26 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:27 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:28 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:29 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:29 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:30 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:31 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:32 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:32 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:33 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:34 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:35 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:35 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:36 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:37 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 4 -
127.0.0.1 - - [15/Feb/2023:19:04:38 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 2 -
127.0.0.1 - - [15/Feb/2023:19:04:38 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:39 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 4 -
127.0.0.1 - - [15/Feb/2023:19:04:40 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:41 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:41 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:42 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 1 -
127.0.0.1 - - [15/Feb/2023:19:04:43 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 4 -
127.0.0.1 - - [15/Feb/2023:19:04:44 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:44 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 4 -
127.0.0.1 - - [15/Feb/2023:19:04:45 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:46 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:47 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 6 -
127.0.0.1 - - [15/Feb/2023:19:04:47 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:48 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 6 -
127.0.0.1 - - [15/Feb/2023:19:04:49 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 6 -
127.0.0.1 - - [15/Feb/2023:19:04:50 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:50 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 4 -
127.0.0.1 - - [15/Feb/2023:19:04:51 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:52 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:53 +0100] "POST /openam/jaxrpc/SMSObjectIF HTTP/1.1" 500 5 -
127.0.0.1 - - [15/Feb/2023:19:04:53 +0100] "POST /openam/sessionservice HTTP/1.1" 200 52 1984
127.0.0.1 - - [15/Feb/2023:19:04:53 +0100] "POST /openam/json/global-audit/access?_action=create HTTP/1.1" 201 53 12
127.0.0.1 - - [15/Feb/2023:19:04:53 +0100] "POST /openam/sessionservice HTTP/1.1" 200 22 258
127.0.0.1 - - [15/Feb/2023:19:04:53 +0100] "POST /openam/sessionservice HTTP/1.1" 200 3 2048
```
</details>
